### ISSUE TITLE
Dialog freezes after selecting file / cancelling / closing dialog window in icy_matrix

### ISSUE THREAD

**Issue by 90-008** [yusdacra/rfd#1]
Happens on Linux, others not tested. Might also be related to the Nix env used, so need to test in an usual Linux env first.

**Comment by PolyMeilex** [comment]
It works fine on my Linux system, but I have one idea...
I moved dialog destroy to the end of fn, let's see if this helps in any way:
[My changes](https://github.com/PolyMeilex/rfd/commit/56e057ad1159a344addec8e6ca087c29c9113321)

**Comment by 90-008** [comment]
Tried that but it didn't change anything. Oh yeah btw it looks like the function *does* return, it's just the dialog that freezes and doesn't disappear. Perhaps it's related to where I spawn the dialog? I use `tokio::task::spawn_blocking` to spawn the dialog in a seperate thread. I'll take a look at how `nativefiledialog` works and see if I can come up with something.

**Comment by 90-008** [comment]
Ok, this commit fixes it 68917b525604f22901949438f47e690f66cdb2b9

Need to wait for gtk to cleanup stuff

**Comment by PolyMeilex** [comment]
Yep, I guess it's somehow related to async environment, nice catch
